Repository hmcts/fact-admin, pull requests merged in 2020-11, with the labels that each got.

#51 Add jwt decode
  package.json
  src/main/modules/oidc/index.ts
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-admin-pr-51

#47 Fact 66 update urgent court
  api/court-details.json
  api/courts.json
  api/fact-api-stubs.ts
  src/main/app/controller/courts/EditCourtController.ts
  src/main/app/controller/courts/EditCourtGeneralController.ts
  src/main/app/fact/FactApi.ts
  src/main/modules/awilix/index.ts
  src/main/routes.ts
  src/main/views/courts/courts.njk
  src/main/views/courts/edit-court-general.njk
  src/main/views/courts/edit-court.njk
  src/test/functional/features/court-urgent.feature
  src/test/functional/steps/court-urgent.ts
  src/test/unit/app/controller/courts/EditCourtController.ts
  src/test/unit/app/controller/courts/EditCourtGeneralController.ts
  src/test/unit/app/fact/FactApi.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-47

#63 Fact 210 fix link on edit page
  jest.a11y.config.js
  jest.timeout.config.js
  package.json
  src/main/views/courts/edit-court-general.njk
  src/main/views/webpack/js.njk
Labels: ns:fact, prd:fact, rel:fact-admin-pr-63

#73 Fact 93 general checkboxes
  src/main/app/controller/courts/EditCourtGeneralController.ts
  src/main/views/courts/edit-court-general.njk
  src/test/functional/features/court-open-and-access-scheme.feature
  src/test/functional/steps/court-urgent.ts
  src/test/unit/app/controller/courts/EditCourtGeneralController.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-73
