Repository hmcts/fact-admin, pull requests merged in 2021-07, with the labels that each got.

#267 LaunchDarkly / Feature Flags
  charts/fact-admin/Chart.yaml
  charts/fact-admin/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  infrastructure/main.tf
  package.json
  src/main/modules/featureToggle/index.ts
  src/main/modules/nunjucks/index.ts
  src/main/modules/properties-volume/index.ts
  src/main/server.ts
  src/main/types/FeatureFlagClient.ts
  src/main/utils/LaunchDarkly.ts
  src/test/unit/app/utils/FeatureToggleService.ts
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-admin-pr-267

#287 Refactored functional tests for performance improvements
  src/test/functional/steps/court-types.ts
  src/test/functional/steps/email-addresses.ts
  src/test/functional/steps/opening-hours.ts
  src/test/functional/steps/phone-numbers.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-287

#288 FACT-652 adding bespoke tabs component
  src/main/assets/js/fact-tabs/fact-tabs-index.js
  src/main/assets/js/fact-tabs/fact-tabs.js
  src/main/assets/js/index.ts
  src/main/assets/scss/main.scss
  src/main/assets/scss/scrollbar.scss
  src/main/assets/scss/tabs.scss
  src/main/views/courts/edit-court-general.njk
  src/main/views/courts/tabs/localAuthoritiesContent.njk
  src/main/views/macros/tabs/macro.njk
  src/main/views/macros/tabs/template.njk
  src/test/functional/features/court-types.feature
  src/test/functional/features/email-addresses.feature
  src/test/functional/features/general-info.feature
  src/test/functional/features/local-authorities.feature
  src/test/functional/features/opening-hours.feature
  src/test/functional/features/phone-numbers.feature
  src/test/functional/steps/court-types.ts
  src/test/functional/steps/email-addresses.ts
  src/test/functional/steps/general-info.ts
  src/test/functional/steps/local-authorities.ts
  src/test/functional/steps/opening-hours.ts
  src/test/functional/steps/phone-numbers.ts
  src/test/functional/utlis/puppeteer.util.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-288

#292 FACT-700 - Show application update column in court download
  src/main/app/controller/courts/CourtsDownloadController.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-292

#298 FACT-676 - Add lists page to admin portal
  src/main/app/controller/courts/CourtsDownloadController.ts
  src/main/app/controller/lists/ListsController.ts
  src/main/modules/awilix/index.ts
  src/main/routes.ts
  src/main/views/lists/index.njk
  src/main/views/lists/tabs/localAuthorities.njk
  src/main/views/template.njk
  src/test/unit/app/controller/lists/ListsController.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-298

#278 FACT-582 - Added postcode tab
  package-lock.json
  src/main/app/controller/courts/OpeningTimesController.ts
  src/main/app/controller/courts/PostcodesController.ts
  src/main/app/fact/FactApi.ts
  src/main/assets/js/court-types.ts
  src/main/assets/js/index.ts
  src/main/assets/js/postcodes.ts
  src/main/assets/js/utilities.ts
  src/main/assets/scss/main.scss
  src/main/assets/scss/scrollbar.scss
  src/main/enums/familyAreaOfLaw.ts
  src/main/modules/awilix/index.ts
  src/main/routes.ts
  src/main/types/Postcode.ts
  src/main/views/courts/edit-court-general.njk
  src/main/views/courts/tabs/postcodes.njk
  src/main/views/courts/tabs/postcodesContent.njk
  src/main/views/courts/tabs/typesContent.njk
  src/test/functional/features/postcodes.feature
  src/test/functional/steps/postcodes.ts
  src/test/unit/app/controller/courts/PostcodeController.ts
  src/test/unit/app/fact/FactApi.ts
  src/test/unit/utils/mockResponse.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-278

#303 admin-cleanup - Removed unused controller/view
  src/main/app/controller/courts/CourtDetailsController.ts
  src/main/app/controller/courts/EditCourtController.ts
  src/main/app/fact/FactApi.ts
  src/main/assets/scss/tabs.scss
  src/main/modules/awilix/index.ts
  src/main/routes.ts
  src/main/views/courts/court-details.njk
  src/main/views/courts/courts.njk
  src/test/functional/features/courts.feature
  src/test/functional/steps/courts.ts
  src/test/unit/app/controller/courts/CourtDetailsController.ts
  src/test/unit/app/controller/courts/EditCourtController.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-303

#305 FACT-676 - Add spacing between links on admin portal heading
  src/main/views/template.njk
Labels: ns:fact, prd:fact, rel:fact-admin-pr-305

#309 FACT-774 - Fact court open and access scheme and related changes
  src/test/functional/features/court-additional-information.feature
  src/test/functional/features/court-open-and-access-scheme.feature
  src/test/functional/features/court-urgent.feature
  src/test/functional/features/email-addresses.feature
  src/test/functional/features/general-info.feature
  src/test/functional/features/opening-hours.feature
  src/test/functional/features/phone-numbers.feature
  src/test/functional/steps/court-urgent.ts
  src/test/functional/steps/general-info.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-309

#307 Fact 100 fixes
  src/main/app/controller/courts/PostcodesController.ts
  src/main/assets/js/court-types.ts
  src/main/assets/js/postcodes.ts
  src/main/views/courts/tabs/postcodesContent.njk
  src/test/functional/features/postcodes.feature
  src/test/unit/app/controller/courts/PostcodeController.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-307

#310 Fact 677 - Add in new 'Local Authorities' editing tab
  src/main/app/controller/lists/LocalAuthoritiesListController.ts
  src/main/app/fact/FactApi.ts
  src/main/assets/js/index.ts
  src/main/assets/js/local-authorities-list.ts
  src/main/assets/scss/main.scss
  src/main/modules/awilix/index.ts
  src/main/modules/nunjucks/index.ts
  src/main/routes.ts
  src/main/types/LocalAuthority.ts
  src/main/views/bulk-update/index.njk
  src/main/views/lists/index.njk
  src/main/views/lists/tabs/localAuthorities.njk
  src/main/views/lists/tabs/localAuthoritiesList.njk
  src/main/views/lists/tabs/localAuthoritiesListContent.njk
  src/test/functional/features/list-local-authorities.feature
  src/test/functional/steps/list-local-authorities.ts
  src/test/functional/steps/local-authorities.ts
  src/test/unit/app/controller/lists/LocalAuthortiesListController.ts
  src/test/unit/app/fact/FactApi.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-310

#312 Fact 582-adding some functional test amendments
  src/test/functional/features/postcodes.feature
  src/test/functional/steps/postcodes.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-312

#313 FACT-783 Updated local authorities tab to use new API endpoint for getting all local authorities
  src/main/app/controller/courts/LocalAuthoritiesController.ts
  src/main/app/fact/FactApi.ts
  src/test/unit/app/controller/courts/LocalAuthoritiesController.ts
  src/test/unit/app/fact/FactApi.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-313

#315 Fact 681 - court dynamic search filter
  src/main/assets/js/courts-table-search.ts
  src/main/assets/js/courts.ts
  src/main/assets/js/index.ts
  src/main/assets/scss/main.scss
  src/main/enums/searchToggleState.ts
  src/main/types/CourtItem.ts
  src/main/views/courts/courts.njk
  src/test/functional/features/court-additional-information.feature
  src/test/functional/features/court-open-and-access-scheme.feature
  src/test/functional/features/court-types.feature
  src/test/functional/features/court-urgent.feature
  src/test/functional/features/courts-search-and-sort.feature
  src/test/functional/features/courts.feature
  src/test/functional/features/email-addresses.feature
  src/test/functional/features/general-info.feature
  src/test/functional/features/list-local-authorities.feature
  src/test/functional/features/local-authorities.feature
  src/test/functional/features/opening-hours.feature
  src/test/functional/features/phone-numbers.feature
  src/test/functional/features/postcodes.feature
  src/test/functional/steps/courts-search-and-sort.ts
  src/test/functional/steps/courts.ts
  src/test/functional/utlis/puppeteer.util.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-315
