Repository hmcts/fact-admin, pull requests merged in 2021-06, with the labels that each got.

#254 CVE-2020-28469-Patch - Upgraded glob-parent to 5.1.2
  package.json
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-admin-pr-254

#255 home-remove-patch - Removed unused homepage from admin portal
  src/main/app/controller/HomeController.ts
  src/main/modules/awilix/index.ts
  src/main/routes.ts
  src/main/views/home.njk
  src/test/unit/app/controller/HomeController.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-255

#257 updating package json to resolve high dependencies
  package.json
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-admin-pr-257

#250 FACT-560 Updated phone numbers tab with revised form for adding new entries
  src/main/app/controller/courts/ContactsController.ts
  src/main/assets/js/phone-numbers.ts
  src/main/types/Contact.ts
  src/main/views/courts/tabs/phoneNumbersContent.njk
  src/test/functional/features/phone-numbers.feature
  src/test/functional/steps/phone-numbers.ts
  src/test/functional/utlis/puppeteer.util.ts
  src/test/unit/app/controller/courts/ContactsController.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-250

#260 Amended validation messages and heading for more clarity.
  src/main/app/controller/courts/CourtTypesController.ts
  src/main/views/courts/tabs/typesContent.njk
Labels: ns:fact, prd:fact, rel:fact-admin-pr-260

#251 FACT-579 Updated opening hours tab with revised form for adding new entries
  src/main/app/controller/courts/ContactsController.ts
  src/main/app/controller/courts/OpeningTimesController.ts
  src/main/assets/js/opening-hours.ts
  src/main/types/OpeningTime.ts
  src/main/views/courts/tabs/openingHoursContent.njk
  src/test/functional/features/opening-hours.feature
  src/test/functional/steps/opening-hours.ts
  src/test/functional/steps/phone-numbers.ts
  src/test/functional/utlis/puppeteer.util.ts
  src/test/unit/app/controller/courts/OpeningTimesController.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-251

#262 FACT-574 Updated emails tab with revised form for adding new entries
  src/main/app/controller/courts/EmailsController.ts
  src/main/assets/js/emails.ts
  src/main/types/Email.ts
  src/main/views/courts/tabs/emailsContent.njk
  src/main/views/courts/tabs/typesContent.njk
  src/test/functional/features/email-addresses.feature
  src/test/functional/steps/email-addresses.ts
  src/test/unit/app/controller/courts/EmailsController.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-262

#268 FACT-539 - Prevent duplicated opening hours types being adding to admin portal
  src/main/app/controller/courts/OpeningTimesController.ts
  src/main/types/Error.ts
  src/main/types/OpeningTime.ts
  src/main/utils/validation.ts
  src/main/views/courts/tabs/openingHoursContent.njk
  src/test/functional/features/opening-hours.feature
  src/test/functional/steps/opening-hours.ts
  src/test/functional/utlis/helpers.ts
  src/test/unit/app/controller/courts/OpeningTimesController.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-268

#274 ui-changes - Small changes to email, opening hours and phone numbers …
  src/main/views/courts/tabs/emailsContent.njk
  src/main/views/courts/tabs/openingHoursContent.njk
  src/main/views/courts/tabs/phoneNumbersContent.njk
Labels: ns:fact, prd:fact, rel:fact-admin-pr-274

#275 FACT-563 - Fixed issue with 'View in new window' not opening pages correctly.
  src/main/modules/nunjucks/index.ts
  src/main/views/courts/edit-court-general.njk
Labels: ns:fact, prd:fact, rel:fact-admin-pr-275

#270 FACT-541 Prevent duplicated e-mail addresses on admin portal email tab
  src/main/app/controller/courts/EmailsController.ts
  src/main/app/controller/courts/OpeningTimesController.ts
  src/main/types/Contact.ts
  src/main/types/CourtType.ts
  src/main/types/Element.ts
  src/main/types/Email.ts
  src/main/types/OpeningTime.ts
  src/main/utils/validation.ts
  src/main/views/courts/tabs/emailsContent.njk
  src/test/functional/features/email-addresses.feature
  src/test/functional/steps/email-addresses.ts
  src/test/unit/app/controller/courts/EmailsController.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-270

#241 FACT-292 / FACT-532 Added re-ordering to opening hour entries.
  src/main/assets/js/opening-hours.ts
  src/main/assets/js/utilities.ts
  src/main/views/courts/tabs/openingHoursContent.njk
  src/test/functional/features/opening-hours.feature
  src/test/functional/steps/opening-hours.ts
  src/test/functional/utlis/puppeteer.util.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-241

#272 FACT-293 Add ability to re-order email addresses
  src/main/assets/js/emails.ts
  src/main/views/courts/tabs/emailsContent.njk
  src/test/functional/features/email-addresses.feature
  src/test/functional/steps/email-addresses.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-272

#277 FACT-541 - Login functional test changes
  src/test/functional/steps/login.ts
  src/test/functional/utlis/puppeteer.util.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-277

#279 Added CODEOWNERS file
  .github/CODEOWNERS
Labels: ns:fact, prd:fact, rel:fact-admin-pr-279

#281 Fact 291 1
  src/test/functional/features/opening-hours.feature
  src/test/functional/features/phone-numbers.feature
  src/test/functional/steps/opening-hours.ts
  src/test/functional/steps/phone-numbers.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-281

#282 Added Local Authorities tab
  src/main/app/controller/courts/LocalAuthoritiesController.ts
  src/main/app/fact/FactApi.ts
  src/main/assets/js/court-types.ts
  src/main/assets/js/index.ts
  src/main/assets/js/local-authorities.ts
  src/main/assets/scss/main.scss
  src/main/assets/scss/scrollbar.scss
  src/main/enums/familyAreaOfLaw.ts
  src/main/modules/awilix/index.ts
  src/main/routes.ts
  src/main/types/AreaOfLaw.ts
  src/main/types/LocalAuthority.ts
  src/main/views/courts/edit-court-general.njk
  src/main/views/courts/tabs/localAuthorities.njk
  src/main/views/courts/tabs/localAuthoritiesContent.njk
  src/test/functional/features/court-types.feature
  src/test/functional/features/local-authorities.feature
  src/test/functional/steps/court-types.ts
  src/test/functional/steps/local-authorities.ts
  src/test/unit/app/controller/courts/LocalAuthoritiesController.ts
  src/test/unit/app/fact/FactApi.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-282

#284 FACT-291 Add ability to re-order phone numbers.
  src/main/assets/js/phone-numbers.ts
  src/main/assets/js/utilities.ts
  src/main/views/courts/tabs/phoneNumbersContent.njk
  src/test/functional/features/phone-numbers.feature
  src/test/functional/steps/phone-numbers.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-284

#286 setElementValueForInputField method changed
  src/test/functional/utlis/puppeteer.util.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-286
