Repository hmcts/fact-admin, pull requests merged in 2022-09, with the labels that each got.

#555 Fact 1196
  package.json
  src/main/app/controller/courts/AddressController.ts
  src/main/app/controller/courts/CourtsDownloadController.ts
  src/main/assets/js/addresses.ts
  src/main/types/CourtAddress.ts
  src/main/types/RadioItem.ts
  src/main/views/courts/tabs/addressesContent.njk
  src/test/config.ts
  src/test/functional/features/admin-court-addresses.feature
  src/test/functional/steps/application-progression.ts
  src/test/functional/steps/court-addresses.ts
  src/test/functional/utlis/puppeteer.util.ts
  src/test/smoke/smoke.ts
  src/test/unit/app/controller/courts/AddressController.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-555

#563 adding audits download
  src/main/app/controller/audits/AuditController.ts
  src/main/routes.ts
  src/main/views/audits/auditContent.njk
  src/test/unit/app/controller/audits/AuditController.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-563

#562 enable fortify scan
  Jenkinsfile_nightly
  java/.gitignore
  java/build.gradle
  java/config/fortify-client.properties
  java/gradle/wrapper/gradle-wrapper.jar
  java/gradle/wrapper/gradle-wrapper.properties
  java/gradlew
  java/gradlew.bat
  java/settings.gradle
  package.json
  src/test/functional/features/list-contact-types.feature
Labels: ns:fact, prd:fact, rel:fact-admin-pr-562

#569 updating audit code for vuln
  src/main/assets/js/audits.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-569

#558 FACT-1162 adding feature flags and implement into edit court dropdown
  Jenkinsfile_CNP
  charts/fact-admin/Chart.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  package.json
  src/main/app/controller/courts/EditCourtController.ts
  src/main/app/errors/HttpError.ts
  src/main/app/feature-flags/FeatureFlags.ts
  src/main/app/feature-flags/LaunchDarklyClient.ts
  src/main/app/feature-flags/flags.ts
  src/main/modules/awilix/index.ts
  src/main/modules/nunjucks/index.ts
  src/main/modules/oidc/index.ts
  src/main/modules/properties-volume/index.ts
  src/main/routes.ts
  src/main/server.ts
  src/main/types/CourtPageData.ts
  src/main/utils/error.ts
  src/main/utils/flagPrefix.ts
  src/main/views/courts/edit-court-general.njk
  src/main/views/macros/errorSummary.njk
  src/test/functional/features/additional-links.feature
  src/test/functional/features/admin-audit.feature
  src/test/functional/features/admin-court-addresses.feature
  src/test/functional/features/application-progression.feature
  src/test/functional/features/cases-heard.feature
  src/test/functional/features/court-photo.feature
  src/test/functional/features/court-spoe.feature
  src/test/functional/features/court-types.feature
  src/test/functional/features/court-urgent.feature
  src/test/functional/features/courts.feature
  src/test/functional/features/email-addresses.feature
  src/test/functional/features/facilities.feature
  src/test/functional/features/general-info.feature
  src/test/functional/features/local-authorities.feature
  src/test/functional/features/opening-hours.feature
  src/test/functional/features/phone-numbers.feature
  src/test/functional/features/postcode-order.feature
  src/test/functional/features/postcodes.feature
  src/test/functional/steps/court-urgent.ts
  src/test/functional/steps/opening-hours.ts
  src/test/functional/support/hooks.ts
  src/test/functional/utlis/feature-flag-helper.ts
  src/test/unit/app/controller/courts/EditCourtController.ts
  src/test/unit/app/errors/HttpError.ts
  src/test/unit/app/feature-flags/FeatureFlags.ts
  src/test/unit/app/feature-flags/LaunchDarkly.ts
  src/test/unit/app/utils/FeatureToggleService.ts
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-admin-pr-558
