Repository hmcts/fact-admin, pull requests merged in 2022-10, with the labels that each got.

#573 adding cookie manager
  package.json
  src/main/assets/js/cookie-manager.ts
  src/main/assets/js/index.ts
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-admin-pr-573

#576 updating cookie manager
  src/main/assets/js/cookie-manager.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-576

#574 Alterations to reduce functional test time
  .gitignore
  cucumber.js
  package.json
  src/test/config.ts
  src/test/functional/features/admin/admin-login.feature
  src/test/functional/features/admin/admin-logout.feature
  src/test/functional/features/admin/court-urgent.feature
  src/test/functional/features/admin/courts.feature
  src/test/functional/features/admin/general-info.feature
  src/test/functional/features/admin/phone-numbers.feature
  src/test/functional/features/homepage.feature
  src/test/functional/features/super_admin/additional-links.feature
  src/test/functional/features/super_admin/admin-add-new-court.feature
  src/test/functional/features/super_admin/admin-audit.feature
  src/test/functional/features/super_admin/admin-court-addresses.feature
  src/test/functional/features/super_admin/admin-create-user.feature
  src/test/functional/features/super_admin/application-progression.feature
  src/test/functional/features/super_admin/bulk-update.feature
  src/test/functional/features/super_admin/cases-heard.feature
  src/test/functional/features/super_admin/court-additional-information.feature
  src/test/functional/features/super_admin/court-open-and-access-scheme.feature
  src/test/functional/features/super_admin/court-photo.feature
  src/test/functional/features/super_admin/court-spoe.feature
  src/test/functional/features/super_admin/court-types.feature
  src/test/functional/features/super_admin/courts-search-and-sort.feature
  src/test/functional/features/super_admin/email-addresses.feature
  src/test/functional/features/super_admin/facilities.feature
  src/test/functional/features/super_admin/general-info.feature
  src/test/functional/features/super_admin/list-areas-of-law.feature
  src/test/functional/features/super_admin/list-contact-types.feature
  src/test/functional/features/super_admin/list-facility-types.feature
  src/test/functional/features/super_admin/list-local-authorities.feature
  src/test/functional/features/super_admin/list-opening-types.feature
  src/test/functional/features/super_admin/local-authorities.feature
  src/test/functional/features/super_admin/opening-hours.feature
  src/test/functional/features/super_admin/postcode-order.feature
  src/test/functional/features/super_admin/postcodes.feature
  src/test/functional/puppeteer.config.ts
  src/test/functional/steps/additional-links.ts
  src/test/functional/steps/application-progression.ts
  src/test/functional/steps/cases-heard.ts
  src/test/functional/steps/court-photo.ts
  src/test/functional/steps/court-spoe.ts
  src/test/functional/steps/court-types.ts
  src/test/functional/steps/email-addresses.ts
  src/test/functional/steps/facilities.ts
  src/test/functional/steps/general-info.ts
  src/test/functional/steps/login.ts
  src/test/functional/steps/logout.ts
  src/test/functional/steps/opening-hours.ts
  src/test/functional/steps/phone-numbers.ts
  src/test/functional/steps/postcodes.ts
  src/test/functional/support/hooks.ts
  src/test/functional/utlis/puppeteer.util.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-574

#580 test
  package.json
  src/test/config.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-580

#583 FACT-1178 fixed postcodes toString issue on fact admin side
  src/main/app/controller/courts/AddressController.ts
  src/main/app/controller/courts/PostcodesController.ts
  src/test/unit/app/controller/courts/AddressController.ts
  src/test/unit/app/controller/courts/PostcodeController.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-583

#582 sanitize html for nightly builds, and remove is element checks where not needed
  package.json
  src/main/app/controller/audits/AuditController.ts
  src/test/functional/steps/email-addresses.ts
  src/test/functional/steps/postcodes.ts
  src/test/unit/app/controller/audits/AuditController.ts
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-admin-pr-582

#578 updating cookie-manager.ts
  charts/fact-admin/Chart.yaml
  charts/fact-admin/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  src/main/assets/js/cookie-manager.ts
  src/main/modules/session/index.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-578

#585 adding fact viewer changes for admin portal
  Jenkinsfile_CNP
  cucumber.js
  src/main/app/controller/courts/LocalAuthoritiesController.ts
  src/main/app/controller/courts/PostcodesController.ts
  src/main/modules/oidc/index.ts
  src/main/views/courts/courts.njk
  src/main/views/courts/edit-court-general.njk
  src/main/views/courts/tabs/localAuthoritiesContent.njk
  src/main/views/courts/tabs/postcodesContent.njk
  src/test/config.ts
  src/test/functional/features/super_admin/admin-audit.feature
  src/test/functional/features/viewer/viewer-login.feature
  src/test/functional/puppeteer.config.ts
  src/test/functional/steps/login.ts
  src/test/functional/steps/tabs.ts
  src/test/functional/support/hooks.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-585

#587 adding duplicate address validation
  src/main/app/controller/courts/AddressController.ts
  src/test/functional/features/super_admin/admin-court-addresses.feature
  src/test/unit/app/controller/courts/AddressController.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-587
