Repository hmcts/fact-admin, pull requests merged in 2022-04, with the labels that each got.

#484 fix vulnerabilities
  package.json
Labels: ns:fact, prd:fact, rel:fact-admin-pr-484

#487 FACT-1153: Increasing intro character count to 400
  src/main/app/controller/courts/GeneralInfoController.ts
  src/main/views/courts/tabs/generalContent.njk
  src/test/unit/app/controller/courts/GeneralInfoController.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-487

#491 FACT-1153: Increasing char limited to account for html tags
  src/main/app/controller/courts/GeneralInfoController.ts
  src/test/unit/app/controller/courts/GeneralInfoController.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-491
