Repository hmcts/fact-admin, pull requests merged in 2022-08, with the labels that each got.

#539 refactor FactApi.ts
  src/main/app/fact/FactApi.ts
  src/main/app/fact/FactApiBase.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-539

#540 updating audit tests
  src/test/functional/features/admin-audit.feature
  src/test/functional/steps/admin-audit.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-540

#544 Fact remove redirect
  src/main/app/controller/courts/CourtsController.ts
  src/main/modules/oidc/index.ts
  src/main/server.ts
  src/main/views/redirect.njk
Labels: ns:fact, prd:fact, rel:fact-admin-pr-544

#545 saving session
  jest.timeout.config.js
  src/main/modules/oidc/index.ts
  src/main/views/logout.njk
  src/test/a11y/a11y.ts
  src/test/functional/steps/logout.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-545

#546 commit
  src/main/assets/js/bulk-update.ts
  src/main/assets/js/index.ts
  src/main/views/bulk-update/index.njk
  src/test/functional/features/bulk-update.feature
  src/test/functional/steps/bulk-update.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-546

#548 adding disabled save buttons on all tabs when service is down
  src/main/app/controller/courts/AdditionalLinksController.ts
  src/main/app/controller/courts/ApplicationProgressionController.ts
  src/main/app/controller/courts/CasesHeardController.ts
  src/main/app/controller/courts/ContactsController.ts
  src/main/app/controller/courts/CourtFacilitiesController.ts
  src/main/app/controller/courts/CourtSpoeController.ts
  src/main/app/controller/courts/CourtTypesController.ts
  src/main/app/controller/courts/EmailsController.ts
  src/main/app/controller/courts/GeneralInfoController.ts
  src/main/app/controller/courts/LocalAuthoritiesController.ts
  src/main/app/controller/courts/NewCourtController.ts
  src/main/app/controller/courts/OpeningTimesController.ts
  src/main/app/controller/courts/PostcodesController.ts
  src/main/types/AdditionalLink.ts
  src/main/types/ApplicationProgression.ts
  src/main/types/CasesHeardPageData.ts
  src/main/types/Contact.ts
  src/main/types/CourtGeneralInfo.ts
  src/main/types/CourtType.ts
  src/main/types/Email.ts
  src/main/types/Facility.ts
  src/main/types/LocalAuthority.ts
  src/main/types/OpeningTime.ts
  src/main/types/Postcode.ts
  src/main/types/SpoeAreaOfLawPageData.ts
  src/main/views/courts/addNewCourt.njk
  src/main/views/courts/tabs/additionalLinksContent.njk
  src/main/views/courts/tabs/applicationProgressionContent.njk
  src/main/views/courts/tabs/casesHeardContent.njk
  src/main/views/courts/tabs/emailsContent.njk
  src/main/views/courts/tabs/facilitiesContent.njk
  src/main/views/courts/tabs/generalContent.njk
  src/main/views/courts/tabs/localAuthoritiesContent.njk
  src/main/views/courts/tabs/openingHoursContent.njk
  src/main/views/courts/tabs/phoneNumbersContent.njk
  src/main/views/courts/tabs/postcodesContent.njk
  src/main/views/courts/tabs/spoeContent.njk
  src/main/views/courts/tabs/typesContent.njk
  src/test/unit/app/controller/courts/AdditionalLinksController.ts
  src/test/unit/app/controller/courts/ApplicationProgressionController.ts
  src/test/unit/app/controller/courts/CasesHeardController.ts
  src/test/unit/app/controller/courts/ContactsController.ts
  src/test/unit/app/controller/courts/CourtFacilitiesController.ts
  src/test/unit/app/controller/courts/CourtTypesController.ts
  src/test/unit/app/controller/courts/CourtsSpoeController.ts
  src/test/unit/app/controller/courts/EmailsController.ts
  src/test/unit/app/controller/courts/GeneralInfoController.ts
  src/test/unit/app/controller/courts/LocalAuthoritiesController.ts
  src/test/unit/app/controller/courts/NewCourtController.ts
  src/test/unit/app/controller/courts/OpeningTimesController.ts
  src/test/unit/app/controller/courts/PostcodeController.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-548

#551 courts page error message
  src/main/app/controller/courts/CourtsController.ts
  src/main/views/courts/courts.njk
  src/test/unit/app/controller/courts/CourtsController.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-551

#553 links not appearing
  src/main/views/courts/edit-court-general.njk
Labels: ns:fact, prd:fact, rel:fact-admin-pr-553

#552 Add backstage configuration file
  catalog-info.yaml
Labels: ns:fact, prd:fact, rel:fact-admin-pr-552
