Repository hmcts/fact-admin, pull requests merged in 2022-01, with the labels that each got.

#414 Fact 950 3
  .eslintrc.js
  README.md
  src/main/app/controller/audits/AuditController.ts
  src/main/app/controller/courts/NewCourtController.ts
  src/main/app/controller/courts/PhotoController.ts
  src/main/app/fact/FactApi.ts
  src/main/assets/js/add-new-court.ts
  src/main/assets/js/audits.ts
  src/main/assets/js/index.ts
  src/main/modules/awilix/index.ts
  src/main/modules/nunjucks/index.ts
  src/main/routes.ts
  src/main/types/NewCourt.ts
  src/main/views/courts/addNewCourt.njk
  src/main/views/template.njk
  src/test/functional/features/admin-add-new-court.feature
  src/test/functional/features/admin-audit.feature
  src/test/functional/steps/admin-add-new-court.ts
  src/test/functional/support/hooks.ts
  src/test/unit/app/controller/courts/NewCourtController.ts
  src/test/unit/app/fact/FactApi.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-414

#416 Fact 1050
  charts/fact-admin/Chart.yaml
  charts/fact-admin/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  src/main/modules/oidc/index.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-416

#415 Fact 980
  src/main/app/controller/courts/GeneralInfoController.ts
  src/main/views/courts/tabs/generalContent.njk
  src/test/unit/app/controller/courts/GeneralInfoController.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-415

#418 FACT-980: enabling links to be pasted and cleaning up duplicated code
  package.json
  src/main/assets/js/courtGeneralInfo.ts
  src/main/assets/js/facilities.ts
  src/main/assets/js/tinymce.config.ts
  src/main/assets/js/utilities.ts
  src/test/functional/features/facilities.feature
  src/test/functional/steps/facilities.ts
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-admin-pr-418

#420 Fact 1051
  src/main/modules/helmet/index.ts
  src/main/modules/session/index.ts
  src/main/server.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-420

#421 FACT-980: Removing bold, italic and underline options from urgent not…
  src/main/assets/js/utilities.ts
  src/main/views/courts/tabs/generalContent.njk
Labels: ns:fact, prd:fact, rel:fact-admin-pr-421

#427 changing text on page around puas
  package.json
  src/main/views/courts/tabs/generalContent.njk
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-admin-pr-427

#429 updates to code to allow for puas to be checked if in person is false…
  src/main/app/controller/courts/GeneralInfoController.ts
  src/main/views/courts/tabs/generalContent.njk
Labels: ns:fact, prd:fact, rel:fact-admin-pr-429
