Repository hmcts/fact-admin, pull requests merged in 2023-03, with the labels that each got.

#617 FACT-1263 fixed bug for removing new lines from validation rule
  src/main/utils/validation.ts
  src/test/unit/app/utils/validation.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-617

#618 Updating terraform
  infrastructure/.terraform-version
  infrastructure/state.tf
  infrastructure/variables.tf
Labels: ns:fact, prd:fact, add-or-update, rel:fact-admin-pr-618

#619 fix error message court name format
  src/main/app/controller/courts/EditCourtController.ts
  src/test/functional/features/super_admin/court-lock.feature
  src/test/unit/app/controller/courts/EditCourtController.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-619
