Repository hmcts/fact-admin, pull requests merged in 2023-05, with the labels that each got.

#627 functional test amendment
  src/test/functional/steps/login.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-627

#628 sonarcloud fixes
  src/main/app/controller/courts/AdditionalLinksController.ts
  src/main/app/controller/courts/ApplicationProgressionController.ts
  src/main/app/controller/courts/ContactsController.ts
  src/main/app/controller/courts/CourtFacilitiesController.ts
  src/main/app/controller/courts/CourtTypesController.ts
  src/main/app/controller/courts/EmailsController.ts
  src/main/app/controller/courts/GeneralInfoController.ts
  src/main/app/controller/courts/OpeningTimesController.ts
  src/main/app/controller/lists/AreasOfLawController.ts
  src/main/app/controller/lists/ContactTypesController.ts
  src/main/app/controller/lists/FacilityTypesController.ts
  src/main/app/controller/lists/OpeningTypesController.ts
  src/main/app/feature-flags/LaunchDarklyClient.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-628

#630 added ld fix for sonarcloud
  src/main/app/feature-flags/LaunchDarklyClient.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-630

#631 sonarcloud fix 2
  src/main/app/feature-flags/LaunchDarklyClient.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-631

#632 sonarcloud fix 3
  .nvmrc
  Dockerfile
  package.json
  src/main/app/feature-flags/LaunchDarklyClient.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-632

#634 sonarcloud ignore launchdarkly
  sonar-project.properties
  src/main/app/feature-flags/LaunchDarklyClient.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-634

#629 FACT-1300 show error message for users with incorrect roles
  Jenkinsfile_CNP
  src/main/app/controller/courts/CourtsController.ts
  src/main/modules/oidc/index.ts
  src/main/utils/error.ts
  src/main/utils/roles.ts
  src/main/views/template.njk
  src/test/functional/features/admin/admin-login.feature
  src/test/functional/features/admin/court-urgent.feature
  src/test/functional/features/super_admin/admin-court-addresses.feature
  src/test/functional/features/super_admin/court-spoe.feature
  src/test/functional/features/super_admin/local-authorities.feature
  src/test/functional/features/viewer/viewer-login.feature
  src/test/functional/puppeteer.config.ts
  src/test/functional/steps/court-urgent.ts
  src/test/functional/steps/login.ts
  src/test/functional/support/hooks.ts
  src/test/unit/app/controller/courts/CourtsController.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-629

#640 DTSPO-13810 reschedule jenkins nightly builds
  Jenkinsfile_nightly
Labels: ns:fact, prd:fact, rel:fact-admin-pr-640

#638 trying to check users login
  package.json
  src/test/functional/features/super_admin/additional-links.feature
  src/test/functional/features/super_admin/admin-court-addresses.feature
  src/test/functional/features/viewer/viewer-login.feature
  src/test/functional/steps/court-addresses.ts
  src/test/functional/steps/courts.ts
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-admin-pr-638

#636 update packages
  package.json
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-admin-pr-636
