Repository hmcts/fact-admin, pull requests merged in 2024-02, with the labels that each got.

#682 FACT-1592 fact admin fix fortify issues
  .yarn/install-state.gz
  charts/fact-admin/Chart.yaml
  java/build.gradle
  src/main/modules/properties-volume/index.ts
  src/test/functional/features/super_admin/admin-audit.feature
Labels: ns:fact, prd:fact, rel:fact-admin-pr-682

#687 Accessibility WCAG FACT 1.4.10: Reflow
  README.md
  src/main/views/courts/courts.njk
  src/test/functional/features/super_admin/facilities.feature
Labels: ns:fact, prd:fact, rel:fact-admin-pr-687

#688 FACT Admin 1493 - Headings and Labels
  src/main/views/bulk-update/index.njk
  src/main/views/courts/addNewCourt.njk
  src/main/views/lists/tabs/localAuthoritiesListContent.njk
Labels: ns:fact, prd:fact, rel:fact-admin-pr-688

#686 FACT-1492 Updating page titles
  src/main/views/audits/index.njk
  src/main/views/bulk-update/index.njk
  src/main/views/courts/addNewCourt.njk
  src/main/views/courts/courts.njk
  src/main/views/error.njk
  src/main/views/lists/index.njk
  src/main/views/not-found.njk
  yarn-audit-known-issues
Labels: ns:fact, prd:fact, rel:fact-admin-pr-686

#689 FACT-1496 Updates to avoid confusion to screen reader users
  src/main/views/bulk-update/index.njk
  src/main/views/courts/courts.njk
  src/main/views/courts/tabs/openingHoursContent.njk
Labels: ns:fact, prd:fact, rel:fact-admin-pr-689

#691 Accessibility WCAG FACT 2.1.1: Keyboard
  src/main/assets/js/courts.ts
  src/main/assets/js/fact-tabs/fact-tabs.js
  src/main/assets/scss/tabs.scss
  src/main/views/courts/courts.njk
Labels: ns:fact, prd:fact, rel:fact-admin-pr-691

#694 FACT-1499 changed warning text to GDS warning text component
  .yarn/install-state.gz
  src/main/views/bulk-update/index.njk
Labels: ns:fact, prd:fact, rel:fact-admin-pr-694

#692 Usability issue 1: Fact Admin
  .yarn/install-state.gz
  src/main/views/courts/tabs/additionalLinksContent.njk
  src/main/views/courts/tabs/addressesContent.njk
  src/main/views/courts/tabs/applicationProgressionContent.njk
  src/main/views/courts/tabs/deletePhotoConfirm.njk
  src/main/views/courts/tabs/emailsContent.njk
  src/main/views/courts/tabs/facilitiesContent.njk
  src/main/views/courts/tabs/openingHoursContent.njk
  src/main/views/courts/tabs/phoneNumbersContent.njk
  src/main/views/courts/tabs/postcodesContent.njk
  src/main/views/courts/tabs/typesContent.njk
  src/main/views/lists/tabs/contactTypes/deleteContactTypeConfirm.njk
  src/main/views/lists/tabs/deleteAreaOfLawConfirm.njk
  src/main/views/lists/tabs/deleteFacilityTypeConfirm.njk
  src/main/views/lists/tabs/openingTypes/deleteOpeningTypeConfirm.njk
Labels: ns:fact, prd:fact, rel:fact-admin-pr-692

#695 Fact 1628
  .pnp.cjs
  .yarn/cache/govuk-frontend-npm-4.5.0-077ac6cb8b-7a999ffb49.zip
  .yarn/cache/govuk-frontend-npm-4.8.0-48d4f1031d-e255f924f3.zip
  package.json
  src/main/views/template.njk
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-admin-pr-695

#693 FACT Admin 1498 - Error Fix Suggestion Linking to Input Field
  src/main/app/controller/courts/NewCourtController.ts
  src/main/app/controller/lists/LocalAuthoritiesListController.ts
  src/main/enums/newCourtErrorMessage.ts
  src/main/views/courts/addNewCourt.njk
  src/main/views/lists/tabs/localAuthoritiesListContent.njk
  src/test/functional/features/super_admin/admin-add-new-court.feature
  src/test/functional/steps/admin-add-new-court.ts
  src/test/unit/app/controller/courts/NewCourtController.ts
  src/test/unit/app/controller/lists/LocalAuthortiesListController.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-693
