Repository hmcts/fact-admin, pull requests merged in 2024-04, with the labels that each got.

#711 disabled fortify scan
  .pnp.cjs
  .yarn/cache/body-parser-npm-1.20.1-759fd14db9-f1050dbac3.zip
  .yarn/cache/express-npm-4.18.2-bb15ff679a-3c4b9b0768.zip
  .yarn/cache/follow-redirects-npm-1.15.5-9d14db76ca-5ca49b5ce6.zip
  .yarn/cache/raw-body-npm-2.5.1-9dd1d9fff9-5362adff15.zip
  .yarn/cache/tinymce-npm-6.8.3-0ff3e2bee5-2ce922ceb6.zip
  .yarn/install-state.gz
  Jenkinsfile_nightly
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-admin-pr-711

#704 FACT-1635 usability fix for fact-admin
  .nvmrc
  .pnp.cjs
  .yarn/cache/@panva-asn1.js-npm-1.0.0-2bf51df722-cb6bcc1918.zip
  .yarn/cache/ip-npm-2.0.0-204facb3cc-cfcfac6b87.zip
  .yarn/cache/jose-npm-2.0.6-28b3274077-c13a95f38f.zip
  .yarn/cache/jose-npm-4.15.4-c518ec3da8-dccad91cb3.zip
  .yarn/cache/nanoid-npm-3.3.4-3d250377d6-2fddd6dee9.zip
  .yarn/cache/postcss-npm-8.4.14-c0d448b728-fe58766ff3.zip
  .yarn/install-state.gz
  src/main/app/controller/bulk-update/BulkUpdateController.ts
  src/main/app/controller/courts/GeneralInfoController.ts
  src/main/types/CourtGeneralInfo.ts
  src/main/utils/validation.ts
  src/main/views/bulk-update/index.njk
  src/main/views/courts/tabs/generalContent.njk
  src/test/unit/app/controller/courts/GeneralInfoController.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-admin-pr-704

#716 Update Node Chart.yaml
  charts/fact-admin/Chart.yaml
Labels: ns:fact, prd:fact, rel:fact-admin-pr-716

#717 update dependencies
  .pnp.cjs
  .yarn/cache/express-openid-connect-npm-2.13.0-80bd22325a-36f580794a.zip
  .yarn/cache/express-openid-connect-npm-2.17.1-ab6b29f7f6-96c27f8e1a.zip
  .yarn/cache/postcss-npm-8.4.38-495621b279-649f9e60a7.zip
  .yarn/cache/source-map-js-npm-1.2.0-6e63f357e5-791a43306d.zip
  .yarn/install-state.gz
  package.json
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-admin-pr-717
