Repository hmcts/fact-admin, pull requests merged in 2024-09, with the labels that each got.

#745 updated test config
  package.json
  src/test/config.ts
  src/test/functional/codecept-features/admin/courts.feature
  src/test/functional/codecept-features/admin/phone-numbers.feature
  src/test/functional/codecept-features/super_admin/additional-links.feature
  src/test/functional/codecept-features/super_admin/admin-add-new-court.feature
  src/test/functional/codecept-features/super_admin/admin-audit.feature
  src/test/functional/codecept-features/super_admin/admin-court-addresses.feature
  src/test/functional/codecept-features/super_admin/cases-heard.feature
  src/test/functional/codecept-features/super_admin/court-spoe.feature
  src/test/functional/codecept-features/super_admin/court-types.feature
  src/test/functional/codecept-features/super_admin/email-addresses.feature
  src/test/functional/codecept-features/super_admin/list-areas-of-law.feature
  src/test/functional/codecept-features/super_admin/opening-hours.feature
  src/test/functional/codecept.conf.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-745

#740 FACT-1920 Background Steps Fix
  package.json
  src/test/config.ts
  src/test/functional/codecept-features/admin/court-urgent.feature
  src/test/functional/codecept-features/admin/courts.feature
  src/test/functional/codecept-features/admin/phone-numbers.feature
  src/test/functional/codecept-features/super_admin/additional-links.feature
  src/test/functional/codecept-features/super_admin/admin-add-new-court.feature
  src/test/functional/codecept-features/super_admin/admin-audit.feature
  src/test/functional/codecept-features/super_admin/admin-court-addresses.feature
  src/test/functional/codecept-features/super_admin/application-progression.feature
  src/test/functional/codecept-features/super_admin/bulk-update.feature
  src/test/functional/codecept-features/super_admin/cases-heard.feature
  src/test/functional/codecept-features/super_admin/court-photo.feature
  src/test/functional/codecept-features/super_admin/court-spoe.feature
  src/test/functional/codecept-features/super_admin/court-types.feature
  src/test/functional/codecept-features/super_admin/courts-search-and-sort.feature
  src/test/functional/codecept-features/super_admin/email-addresses.feature
  src/test/functional/codecept-features/super_admin/facilities.feature
  src/test/functional/codecept-features/super_admin/general-info.feature
  src/test/functional/codecept-features/super_admin/list-areas-of-law.feature
  src/test/functional/codecept-features/super_admin/list-contact-types.feature
  src/test/functional/codecept-features/super_admin/list-facility-types.feature
  src/test/functional/codecept-features/super_admin/list-local-authorities.feature
  src/test/functional/codecept-features/super_admin/list-opening-types.feature
  src/test/functional/codecept-features/super_admin/local-authorities.feature
  src/test/functional/codecept-features/super_admin/opening-hours.feature
  src/test/functional/codecept-features/super_admin/postcodes.feature
  src/test/functional/codecept-features/viewer/viewer-login.feature
  src/test/functional/codecept-steps/court-urgent.ts
  src/test/functional/codecept.conf.ts
  yarn-audit-known-issues
Labels: ns:fact, prd:fact, rel:fact-admin-pr-740

#751 FACT-1947 redo known issues
  yarn-audit-known-issues
Labels: ns:fact, prd:fact, rel:fact-admin-pr-751

#752 FACT-1947 fixing last dependancies
  .pnp.cjs
  .yarn/cache/ip-npm-2.0.1-ee48691f03-d765c9fd21.zip
  .yarn/install-state.gz
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-admin-pr-752

#747 FACT-1957 Remove Court Lock
  src/main/app/controller/courts/CourtsController.ts
  src/main/routes.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-747

#748 FACT-1958 remove court lock on logout
  src/main/app/controller/LogoutController.ts
  src/main/modules/awilix/index.ts
  src/main/modules/oidc/index.ts
  src/main/routes.ts
  src/test/unit/app/controller/LogoutController.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-748
