Repository hmcts/fact-admin, pull requests merged in 2025-03, with the labels that each got.

#781 FACT-2203 - More Descriptive Page Titles
  src/main/modules/nunjucks/index.ts
  src/main/modules/nunjucks/njkFilters.ts
  src/main/views/audits/index.njk
  src/main/views/bulk-update/index.njk
  src/main/views/courts/addNewCourt.njk
  src/main/views/courts/courts.njk
  src/main/views/courts/edit-court-general.njk
  src/main/views/error.njk
  src/main/views/lists/index.njk
  src/main/views/not-found.njk
  src/test/functional/features/admin/application-progression.feature
  src/test/functional/features/admin/courts.feature
  src/test/functional/features/admin/general-info.feature
  src/test/functional/features/admin/phone-numbers.feature
  src/test/functional/features/super_admin/additional-links.feature
  src/test/functional/features/super_admin/admin-audit.feature
  src/test/functional/features/super_admin/admin-court-addresses.feature
  src/test/functional/features/super_admin/cases-heard.feature
  src/test/functional/features/super_admin/court-additional-information.feature
  src/test/functional/features/super_admin/court-open-and-access-scheme.feature
  src/test/functional/features/super_admin/court-photo.feature
  src/test/functional/features/super_admin/court-spoe.feature
  src/test/functional/features/super_admin/court-types.feature
  src/test/functional/features/super_admin/email-addresses.feature
  src/test/functional/features/super_admin/facilities.feature
  src/test/functional/features/super_admin/general-info.feature
  src/test/functional/features/super_admin/local-authorities.feature
  src/test/functional/features/super_admin/opening-hours.feature
  src/test/functional/features/super_admin/postcode-order.feature
  src/test/functional/features/super_admin/postcodes.feature
  src/test/functional/features/viewer/viewer-login.feature
  src/test/functional/steps/admin-add-new-court.ts
  src/test/functional/steps/bulk-update.ts
  src/test/functional/steps/courts.ts
  src/test/functional/steps/list-local-authorities.ts
  src/test/functional/utlis/helpers.ts
  src/test/unit/app/modules/nunjucks/njkFilters.ts
Labels: ns:fact, prd:fact, rel:fact-admin-pr-781

#777 FACT-2153 Upgrade azurerm to 4.0.0+
  infrastructure/state.tf
  infrastructure/versions.tf
Labels: ns:fact, prd:fact, aat/add-or-update, prod/no-changes, rel:fact-admin-pr-777

#783 FACT-2208 - Removes scrollbar
  src/main/views/courts/addNewCourt.njk
  src/main/views/courts/tabs/addressesContent.njk
  src/main/views/courts/tabs/casesHeardContent.njk
  src/main/views/courts/tabs/postcodesContent.njk
Labels: ns:fact, prd:fact, rel:fact-admin-pr-783

#786 FACT-2207
  src/main/views/courts/courts.njk
Labels: ns:fact, prd:fact, enable_keep_helm, rel:fact-admin-pr-786

#784 FACT-2205 - remove branding from TinyMCE
  src/main/assets/js/tinymce.config.ts
  src/main/assets/js/utilities.ts
  src/main/views/bulk-update/index.njk
  src/main/views/courts/tabs/facilitiesContent.njk
  src/main/views/courts/tabs/generalContent.njk
  src/main/views/macros/_tiny-attribution.njk
Labels: ns:fact, prd:fact, enable_keep_helm, rel:fact-admin-pr-784

#789 FACT-2120 Upgrade Pa11y and fix tests
  .yarn/install-state.gz
  package.json
  src/test/a11y/a11y.ts
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-admin-pr-789

#790 FACT-2293 updates
  .yarn/install-state.gz
  README.md
  charts/fact-admin/Chart.yaml
  package.json
  yarn.lock
Labels: ns:fact, prd:fact, rel:fact-admin-pr-790

#791 FACT-2201 Add context to button labels
  src/main/assets/js/additionalLinks.ts
  src/main/assets/js/addresses.ts
  src/main/assets/js/application-progression.ts
  src/main/assets/js/court-types.ts
  src/main/assets/js/emails.ts
  src/main/assets/js/opening-hours.ts
  src/main/assets/js/phone-numbers.ts
  src/main/views/courts/tabs/additionalLinksContent.njk
  src/main/views/courts/tabs/addressesContent.njk
  src/main/views/courts/tabs/applicationProgressionContent.njk
  src/main/views/courts/tabs/emailsContent.njk
  src/main/views/courts/tabs/openingHoursContent.njk
  src/main/views/courts/tabs/phoneNumbersContent.njk
  src/main/views/courts/tabs/typesContent.njk
Labels: ns:fact, prd:fact, rel:fact-admin-pr-791
