Repository hmcts/fact-admin, pull requests merged in 2025-02, with the labels that each got.

#775 Remove duplicate test runs on yarn test & yarn test:coverage
  package.json
Labels: ns:fact, prd:fact, rel:fact-admin-pr-775

#776 remove idam-pr entirely
  charts/fact-admin/Chart.yaml
Labels: ns:fact, prd:fact, rel:fact-admin-pr-776

#778 NodeJS - upgrade to v22.14.0
  .nvmrc
Labels: ns:fact, prd:fact, rel:fact-admin-pr-778

#782 Update localAuthoritiesContent.njk
  src/main/views/courts/tabs/localAuthoritiesContent.njk
Labels: ns:fact, prd:fact, rel:fact-admin-pr-782
